# Generated by Django 3.2.3 on 2024-01-20 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=40, validators=[django.core.validators.MaxLengthValidator(40, 'Please use less than 40 characters')], verbose_name='Title'),
        ),
    ]
