# Generated by Django 3.2.3 on 2023-11-30 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_comment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='excerpt',
        ),
    ]
