# Generated by Django 3.2.3 on 2024-01-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_remove_post_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tagline',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
