# Generated by Django 3.2.23 on 2023-11-04 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='date_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
    ]
