# Generated by Django 3.2.23 on 2023-11-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20231104_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(verbose_name='Date and Time'),
        ),
    ]
