# Generated by Django 3.2.3 on 2024-01-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_remove_event_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tagline',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
