# Generated by Django 3.2.3 on 2024-01-13 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_tagline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
