# Generated by Django 3.2.23 on 2023-11-04 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, help_text='format: not required, max_length=50', max_length=50, null=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, help_text='format: not required, max_length=50', max_length=50, null=True, verbose_name='Last name')),
                ('company_name', models.TextField(blank=True, max_length=30, null=True)),
                ('location', models.TextField(blank=True, max_length=30, null=True)),
                ('bio', models.TextField(blank=True, max_length=1000, null=True)),
                ('user', models.OneToOneField(help_text='format: required, unique=True', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
