# Generated by Django 3.2.3 on 2023-12-02 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='Full name')),
                ('company_name', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('bio', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
