# Generated by Django 3.2.3 on 2024-01-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_profile_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Full name'),
        ),
    ]
